### ISSUE TITLE
smooch.io & rasa.ai integration (+ bonus deployment scripts)

### ISSUE THREAD

**Issue by ludan-av** [bwilcox-1234/ChatScript#108]
_(as I can't publish on the forum, I put this information here)_

Addventa is a French AI company specialized in Natural Language Generation and chatbots. We love ChatScript and have developped multiple bots with it. We have contributed to the French language support in ChatScript's code.

We have open sourced 3 repos (under MIT licence):

https://github.com/addventa/ChatScriptSmooch: 
Integration of ChatScript with smooch.io.
Smooch.io provides a nice end-user interface (web chat) and can connect to any other channel: facebook messenger, email, SMS etc.
Easy to deploy on heroku or Amazon beanstalk. Works well.

https://github.com/addventa/ChatScriptDeploy: 
Installation scripts of ChatScript on a Linux server. Ability to have multiple versions installed.
Lifecycle of a bot on a ChatScript server: scripts to automate the deployment of a new bot and to update a bot.

https://github.com/addventa/ChatScriptRasa: 
Integration of ChatScript with rasa.ai for intent classification and entity recognition. Comes with a sample bot that calls rasa.ai.

Have worked on that:
- Jean-Baptiste Kerboeuf https://www.chatbots.org/expert/jean_baptiste_kerboeuf/69759/
- Corentin Gaillard https://www.chatbots.org/expert/corentin_gaillard/70268/
- and myself Ludan Stoecklé https://www.linkedin.com/in/ludanstoeckle/

**Comment by solyaris** [comment]
Hi Ludan!

BTW, the forum login issues are solved, I guess.
Maybe it's better to move there, but Thank you for your shares!

Maybe you can add pull request here adding links in a dedicated paragraphs in this doc:
https://github.com/bwilcox-1234/ChatScript/blob/master/Third%20Party%20Tools/README.md

Last but not least, any help in improving wiki documentation here is welcome; I'm available also via mail for possible synchs: giorgio.robino@gmail.com

regards
giorgio

**Comment by ludan-av** [comment]
Thanks Giorgio!

I agree - pull request created: https://github.com/bwilcox-1234/ChatScript/pull/109

Forum issues are not solved yet, I can't login :( I'll do it later.

**Comment by solyaris** [comment]
Thanks to you
 
[off-topic]
yes chatbots.org forum login-process is awful. I complained a bunch of times (website response times too slow). Nevertheless is a great container and history of Bruce's answers.  Immo a forum dedicated to ChatScript could be better...
